### ISSUE TITLE
Errors building project.

### ISSUE THREAD

**Issue by SalmanBurhan** [Imperiopolis/WatchScreenshotMagic#1]
IN DROPIMAGEVIEW.SWIFT
![screen shot 2015-04-12 at 2 15 08 pm](https://cloud.githubusercontent.com/assets/1458577/7107589/64bea560-e11e-11e4-9a56-3809323c2f83.png)
IN THE APP DELEGATE.SWIFT
![screen shot 2015-04-12 at 2 15 53 pm](https://cloud.githubusercontent.com/assets/1458577/7107594/7807ebcc-e11e-11e4-80b8-027c02d8e1d2.png)

**Comment by Imperiopolis** [comment]
The project requires Swift 1.2. Upgrade your Xcode to 6.3 (latest from the App Store) and it will compile.

**Comment by SalmanBurhan** [comment]
Ok, thank you
